modLoader = 'lowcodefml'
loaderVersion = '[46,)'
license="MIT"

[[mods]]
  modId="rebalanced_loot"
  version="1.1"
  displayName="Rebalanced Loot"
  logoFile="pack.png"
  authors="Apollo"
  description='''
  Different chest loot that actually makes sense and isn't overpowered!
  '''

  [[dependencies.rebalanced_loot]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.rebalanced_loot]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"